name: y23
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_phoenix: ^1.1.1
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  hooks_riverpod: ^2.3.6
  image_picker: ^0.8.7+5
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.3.2
  share_plus: ^7.0.1
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translation/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
