class AppStrings {
  static const String appName = "Y23'";
  static const String googleLogin = "google_login";
  static const String login = "login";
  static const String logout = "logout";
  static const String home = "home";
  static const String profile = "profile";
  static const String quizzes = "quizzes";
  static const String settings = "settings";
  static const String sessions = "sessions";
  static const String tasks = "tasks";
  static const String welcome = "welcome";
  static const String loading = "loading";
  static const String help = "help";
  static const String submit = "submit";
  static const String areYouSure = "are_you_sure";
  static const String noQuizzesFound = "no_quizzes_found";
  static const String noSessionsFound = "no_sessions_found";
  static const String noTasksFound = "no_tasks_found";
  static const String noResultsFound = "no_results_found";
  static const String quizzesTaken = "quizzes_taken";
  static const String quizzesPassed = "quizzes_passed";
  static const String score = "score";
  static const String lightMode = "light_mode";
  static const String darkMode = "dark_mode";
  static const String language = "language";
  static const String noInternet = "no_internet";
  static const String wantToAddFeedback = "want_to_add_feedback";
  static const String addFeedback = "add_feedback";
  static const String feedbackAdded = "feedback_added";
  static const String quizSubmitted = "quiz_submitted";
  static const String correct = "correct";
  static const String incorrect = "incorrect";
  static const String notSubmitted = "not_submitted";
  static const String points = "points";
  static const String uploadTask = "upload_task";
  static const String details = "details";
  static const String problemWithLink = "problem_with_link";
  static const String answerAllQuestions = "answer_all_questions";

  const AppStrings._();
}
